### ISSUE TITLE
Certificación

### ISSUE THREAD

**Issue by holamendi** [sagmor/tbk#25]
Hola, alguien que haya usado esta gema para todo el proceso de certificación? Transbank no tiene problemas con eso? O es necesario instalar el kit de todas maneras para certificarse?

Gracias!

**Comment by mariowise** [comment]
Hola! Alguien sabe donde se puede encontrar mas información del mencionado SOAP ??. @cavi21, el link de dropbox esta roto.

**Comment by cavi21** [comment]
@mariowise uh ahi me fijo si los sigo teniendo y los subo de nuevo

**Comment by cavi21** [comment]
@mariowise aca esta subido de nuevo lo que me habían pasado en su momento:
https://www.dropbox.com/s/ts6ua9is9lg09gw/SOAP_TBK.zip?dl=0

**Comment by mariowise** [comment]
Buena! Muchas gracias

**Comment by clsource** [comment]
Sobre Webpay Soap acá documenté más o menos el proceso
https://github.com/clsource/guia-webpay/tree/master/webpay-soap/webpay-oneclick

pero no pude seguir por que el proyecto se canceló y no tuve más acceso al SOAP.

**Comment by bermann** [comment]
Cuando configuré todo en producción me da el siguiente error:

`Errno::ECONNREFUSED (Connection refused - connect(2) for "webpay2g.transbank.cl" port 443):`

El error es en la línea del redirect.

Alguna idea de qué puede ser?

Saludos!

**Comment by isseu** [comment]
Alguien esta desarrollando una gema para SOAP https://github.com/limcross/webpay_rails
Ahora voy a tratar que me den certificación con ella.

**Comment by bermann** [comment]
Lo que pasa es que ya obtuve la certificación, pero al pasar a producción me arroja el error antes mencionado.

**Comment by clsource** [comment]
Ese problema normalmente es ocacionado por qué los certificados usados
están corruptos o son distintos a los que tiene transbank. Verificar que el
certificado enviado a transbank fue sin errores y que los certificados en
la tienda sean los correspondientes.
Saludos

**Comment by patriciojofre** [comment]
@isseu como te ha ido con el tema de la certificación usando esa gema?

**Comment by isseu** [comment]
@patriciojofre Estoy terminando la implementación para enviarlo a certificar. Aviso como me va ..

**Comment by limcross** [comment]
@isseu @patriciojofre Yo ya conseguí pasar la certificación con la [gema](https://github.com/limcross/webpay_rails). 👌
