### ISSUE TITLE
problemas con el ssl

### ISSUE THREAD

**Issue by Janther** [sagmor/tbk#28]
Hola Sagmor,

desde ayer 1 de abril tengo problemas con el certificado SSL que se busca en el método fetch_token de TBK::Webpay::Payment

He intentado varias cosas, entre ellas correr apt-get reinstall ca-certificates pero no logra validar el certificado.

**Comment by Janther** [comment]
investigando llegué a lo siguiente:
la primera url para buscar el token es:
`https://webpay.transbank.cl/filtroUnificado/bp_validacion.cgi`
Este servidor no tiene problemas con su certificado.
Luego redirige a:
`https://webpay3g.transbank.cl/webpayserver/bp_validacion.cgi`
Al revisar este subdominio en [SSLShopper](https://www.sslshopper.com/ssl-checker.html#hostname=https://webpay3g.transbank.cl) podemos notar que falta el certificado intermedio.

**Comment by sagmor** [comment]
Si, son bien weones con la instalación de certificados, cada cierto tiempo (+- una vez al año cuando les toca renovar) lo instalan mal y generan problemas.
